server:
  servlet:
    context-path: /api

spring:
  profiles:
    active: release 

---

spring:
  profiles: release
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://219.244.186.2:3306/qzkk?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: snnucs
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

---

spring:
  profiles: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/qzkk?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8088

